---
- name: Validate Ansible version
  assert:
    that:
     - "{{ ansible_version is defined }}"
     - "{{ ansible_version.full | version_compare(minimum_ansible_version, '>=') }}"
    msg: "Your Ansible version is too old. We require at least {{ minimum_ansible_version }}. Your version is {{ ansible_version.full | default('< 1.6') }}"

- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name="{{ item }}" state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - python-mysqldb
  - python-pip

- name: Install Bitbucket-CLI
  pip: name=bitbucket-cli

- name: Add SSH pub key
  authorized_key: user="vagrant" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  # Install some node modules
- npm: name=gulp global=yes
- npm: name=bower global=yes
- npm: name=yo global=yes
- npm: name=generator-gulp-webapp global=yes
- npm: name=generator-gulp-angular global=yes