---
- name: Check if secrets file exists
  stat: path={{www_root}}/ansible/group_vars/all/secrets_user
  register: secretsfile

- name: Include user secret vars
  include_vars: group_vars/all/secrets_user
  when: secretsfile.stat.exists == True

- name: Check if repo exists
  git: repo=git@bitbucket.org:{{repo_owner}}/{{site_slug}}.git dest={{ www_root }}/sites/{{site_slug }} clone=no update=no accept_hostkey=true
  register: site_repo_status
  ignore_errors: yes
  sudo: false

# IF repo does exist:

- name: Pull repo into correct folder
  git: repo=git@bitbucket.org:{{repo_owner}}/{{site_slug}}.git dest={{ www_root }}/sites/{{site_slug }} accept_hostkey=true version=develop
  sudo: false
  ignore_errors: yes
  when: site_repo_status.stderr is not defined

# IF repo doesn't exist:

- name: Ensure Site's root directory exists.
  file:
    path: "{{ www_root }}/sites/{{ site_slug }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure Site's public directory exists.
  file:
    path: "{{ www_root }}/sites/{{ site_slug }}/public"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Init Bitbucket Repo
  command: git init
  args:
    chdir: "{{ public_root }}/../"
  when: site_repo_status.stderr is defined

- name: Make readme file
  command: touch README.md
  args:
    chdir: "{{ public_root }}/../"
  when: site_repo_status.stderr is defined

- name: Add files to repo
  command: git add -A
  args:
    chdir: "{{ public_root }}/../"
  when: site_repo_status.stderr is defined

- name: Commit files to repo
  command: git commit -m 'Initial commit'
  args:
    chdir: "{{ public_root }}/../"
  when: site_repo_status.stderr is defined

- name: Create Bitbucket Repo
  command: bb create_from_local -u {{vault_bitbucket_user}} -p {{vault_bitbucket_password}} -P ssh -c
  args:
    chdir: "{{ public_root }}/../"
  when: site_repo_status.stderr is defined
  ignore_errors: yes
  sudo: false

# ENDIF
